#!/usr/bin/bash
#
# Provides SmartMachine cpu utilization information.
# Joyent 2012.

usage() {
cat << EOF

Usage: $0 [-p]

Options:
    
    -p               Machine parsable output. 

EOF
exit 2;
}

while getopts "p" OPTION; do
	case $OPTION in
		p)
			MACHINE="YES";
			;;
		*)
			usage;
			;;
	esac
done

PATH="/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin";
SM_UUID=$(zonename);
SM_ID=$(zoneadm list -p | awk -F: '{ print $1 }');

KSTAT_CPU_CAP=$(kstat -p -c zone_caps -n cpucaps_zone_${SM_ID} -s value | awk '{print $2}');
KSTAT_CPU_USED=$(kstat -p -c zone_caps -n cpucaps_zone_${SM_ID} -s usage | awk '{print $2}');
CPU_USED=$(echo -e "scale=2; (${KSTAT_CPU_USED}/${KSTAT_CPU_CAP})*100" | bc 2>/dev/null | sed 's/\.[0-9]*//');
[[ ! ${CPU_USED} ]] && CPU_USED="NA";

CPU_UTIL=$(/usr/bin/prstat -Z 1 1 | /usr/xpg4/bin/awk -v zone=${SM_UUID} '$8 ~ zone { print $7 }' | sed 's/%//g')

echo "* Gathering cpu infomation for ${SM_UUID}..";
[ "${MACHINE}" ] && echo "cpu_used:${CPU_USED}" || echo "CPU Cap Used: ${CPU_USED} %"
[ "${MACHINE}" ] && echo "cpu_util:${CPU_UTIL}" || echo "System CPU Used: ${CPU_UTIL} %"
