#!/usr/bin/bash
#
# Provides vm instance cpu utilization information.
# Copyright (c) 2013 Joyent Inc., All rights reserved.

set -o errexit
set -o pipefail
#set -o nounset
#set -o xtrace

usage() {
	cat <<- EOF >&2

	Usage: $0 [-p]

	Options:
    
        -p               Machine parsable output. 

	EOF

	exit 1;
}

while getopts "p" option; do
	case ${option} in
		p)
			opt_p="true";
			;;
		*)
			usage;
			;;
	esac
done

export LANG=C
PATH="@PREFIX@/bin:@PREFIX@/gnu/bin:@PREFIX@/sbin:/usr/bin:/usr/sbin";
vm_uuid=$(zonename);
vm_id=$(zoneadm list -p | awk -F: '{ print $1 }');

vm_kstat_cpu_cap=$(kstat -p -c zone_caps -n cpucaps_zone_${vm_id} -s value | awk '{print $2}');
vm_kstat_cpu_used=$(kstat -p -c zone_caps -n cpucaps_zone_${vm_id} -s usage | awk '{print $2}');
vm_cpu_cap_used=$(echo -e "scale=2; (${vm_kstat_cpu_used}/${vm_kstat_cpu_cap})*100" | bc 2>/dev/null | sed 's/\.[0-9]*//');
[[ ! ${cpu_used} ]] && cpu_used="NA";

vm_cpu_used=$(prstat -Z 1 1 | awk -v zone=${vm_uuid} '$8 ~ zone { print $7 }' | sed 's/%//g');

echo "* Gathering cpu infomation for ${vm_uuid}..";
[[ "${opt_p}" ]] && echo "cpu_util:${vm_cpu_used}" || echo "CPU Used: ${vm_cpu_used} %";
[[ "${opt_p}" ]] && echo "cpu_used:${vm_cpu_cap_used}" || echo "CPU Cap Used: ${vm_cpu_cap_used} %";
