#!/usr/bin/bash
#
# Installs drupal insto SmartMachine directory. You may need
# to change DP_FILE to what version you need.
# Requirements: Must have HTTP virtual host already setup.
# Joyent 2012. 

usage() {
cat << EOF

Usage: $0 [options] DIRECTORY

Arguments:
    
    DIRECTORY        Directory to install drupal.

Options:
    
    -u               Username to access database.  [use portal credentials]
    -p               Password to access database.  [use portal credentials]

EOF
exit 2;
}

while getopts "u:p:" OPTION; do
        case $OPTION in
                u)
                        DB_USER=$OPTARG;
                        ;;
                p)
                        DB_PASS=$OPTARG;
                        ;;
                *)
                        usage;
                        ;;
        esac
done

shift $(($OPTIND - 1))
if [[ $# = 1 ]]; then
        DP_DIR=$1;
else
        usage;
fi

PATH="/opt/local/bin:/opt/local/gnu/bin:/opt/local/sbin:/usr/bin:/usr/sbin";
DP_USER=dp_$(zonename | awk -F\- '{ print $5 }');
DP_PASS=$(od -An -N8 -x /dev/random | head -1 | sed 's/^[ \t]*//' | tr -d ' ');
DP_DB=dp_$(od -An -N3 -x /dev/random | head -1 | sed 's/^[ \t]*//' | tr -d ' ');
DP_FILE="drupal-7.12.tar.gz";
DP_URL="http://ftp.drupal.org/files/projects/${DP_FILE}";

hash wget &>/dev/null
[[ $? -eq 1 ]] && echo "* ERROR - wget was not found in your PATH." && exit 2;

hash gtar &>/dev/null
[[ $? -eq 1 ]] && echo "* ERROR - gtar was not found in your PATH." && exit 2;

hash gsed &>/dev/null
[[ $? -eq 1 ]] && echo "* ERROR - gsed was not found in your PATH." && exit 2;

hash sm-create-db &>/dev/null
[[ $? -eq 1 ]] && echo "* ERROR - sm-create-db was not found in your PATH." && exit 2;

hash sm-create-dbuser &>/dev/null
[[ $? -eq 1 ]] && echo "* ERROR - sm-create-dbuser was not found in your PATH." && exit 2;

[[ ! -d ${DP_DIR} ]] && echo "* ERROR - Directory ${DP_DIR} doesn't exist." && exit 2;

echo "* Downloading latest drupal.";

wget ${DP_URL} -O ${DP_DIR}/${DP_FILE} > /dev/null 2>&1
[[ $? > 0 ]] && echo "* ERROR - There was an error getting ${DP_URL}." && exit 2;

gtar zxvf ${DP_DIR}/${DP_FILE} -C ${DP_DIR} --strip=1 > /dev/null 2>&1
[[ $? > 0 ]] && echo "* ERROR - There was an error extracting ${DP_FILE} to ${DP_DIR}." && exit 2;

echo "* Configuring drupal.";

cp ${DP_DIR}/sites/default/default.settings.php ${DP_DIR}/sites/default/settings.php
chown -R www:www ${DP_DIR}
chmod 666 ${DP_DIR}/sites/default/settings.php

sm-create-db mysql ${DP_DB}

sm-create-dbuser mysql ${DP_USER} ${DP_PASS} ${DP_DB}

echo "* Visit http://x.x.x.x/install.php to finish the install.";
