#!/usr/bin/bash
#
# List timezones available in a VM.
# Copyright (c) 2016 Joyent Inc., All rights reserved.

export LANG=C
PATH="@PREFIX@/bin:@PREFIX@/gnu/bin:@PREFIX@/sbin:/usr/bin:/usr/sbin";
vm_uuid=$(zonename);

echo "* Listing timezones for ${vm_uuid}..";

find /usr/share/lib/zoneinfo -type f | awk -F/usr/share/lib/zoneinfo/ '{ print $2 }' | egrep -v "src/|.tab"
