#!/usr/bin/bash
#
# Provides SmartMachine memory utilization information.
# Joyent 2012.

usage() {
cat << EOF

Usage: $0 [options] TYPE

Arguments:
    
    TYPE             rss or swap.

Options:
    
    -p               Machine parsable output. 

EOF
exit 2;
}

while getopts "p" OPTION; do
	case $OPTION in
		p)
			machine="YES";
			;;
		*)
			usage;
			;;
	esac
done

shift $(($OPTIND - 1))
if [[ $# = 1 ]]; then
	TYPE=$1;
else
	usage;
fi

PATH="/opt/local/bin:/opt/local/gnu/bin:/opt/local/sbin:/usr/bin:/usr/sbin";
zone=$(zonename);
zoneid=$(zoneadm list -p | awk -F: '{print $1}')

function get_swap_cap {
        swap_cap=$( kstat -p -c zone_caps -n swapresv_zone_$zoneid -s value | awk '{print $2}' )
}
function get_virt_used {
        virt_used=$( kstat -p -c zone_caps -n swapresv_zone_$zoneid -s usage | awk '{print $2}' )
}
function get_tmp_used {
        tmp_used=$( df -k /tmp | /usr/xpg4/bin/awk '{ if ($1 ~ /swap/) print $3}' )
}
function get_mem_cap {
        mem_cap=$( kstat -p -c zone_caps -n lockedmem_zone_$zoneid -s value | awk '{print $2}' )
        if [ $(echo "v=$mem_cap;t=137438953472;r=0;if(v>t)r=1;r"|bc) -gt 0 ]
        then
                get_swap_cap
                case $swap_cap in
                        536870912) mem_cap=268435456;;
                        1073741824) mem_cap=536870912;;
                        2147483648) mem_cap=1073741824;;
                        4294967296) mem_cap=2147483648;;
                        6442450944) mem_cap=4294967296;;
                        12884901888) mem_cap=8589934592;;
                        25769803776) mem_cap=17179869184;;
                        51539607552) mem_cap=34359738368;;
                        *) mem_cap=$((swap_cap/2));
                esac
        fi
}
function get_mem_used {
        mem_used=$( /usr/bin/prstat -Z -s rss 1 1 | \
                   /usr/xpg4/bin/awk -v zone=$zone '$8 ~ zone { rss = $4+0 } END {print (rss*1024*1024)}' )
}
function convert {
        value=$1
        if [ "$machine" ]; then converted=$value
        else
                units=(B KiB MiB GiB TiB)
                index=0
                converted="$1 ${units[$index]}"
                while [ $value -ge 1024 ]
                do
                        index=$(($index+1))
                        value=$(echo -e "scale=1; $value/1024" | bc)
                        converted="$value ${units[$index]}"
                        value=${value%\.*}
                done
        fi
}

case ${TYPE} in
rss)
	echo "* Gathering rss memory infomation for $zone..";
        get_mem_cap
        get_mem_used
        [ "$machine" ] && echo -n "mem_cap:" || echo -n "Memory cap: "
        convert $mem_cap && echo $converted
        [ "$machine" ] && echo -n "mem_used:" || echo -n "Memory used: "
        convert $mem_used && echo $converted
        [ "$machine" ] && echo -n "mem_free:" || echo -n "Memory free: "
        convert $(($mem_cap-$mem_used)) && echo $converted
        ;;
swap)
	echo "* Gathering swap memory infomation for $zone..";
        get_swap_cap
        get_virt_used
        get_tmp_used
        swap_used=$(( $virt_used + $tmp_used ))
        [ "$machine" ] && echo -n "swap_cap:" || echo -n "Swap cap: "
        convert $swap_cap && echo $converted
        [ "$machine" ] && echo -n "virt_used:" || echo -n "Virtual memory used: "
        convert $virt_used && echo $converted
        [ "$machine" ] && echo -n "tmp_used:" || echo -n "/tmp used: "
        convert $tmp_used && echo $converted
        [ "$machine" ] && echo -n "swap_used:" || echo -n "Total swap used: "
        convert $swap_used && echo $converted
        [ "$machine" ] && echo -n "swap_free:" || echo -n "Total swap free: "
        convert $(($swap_cap-$swap_used)) && echo $converted
        ;;
*)
	usage;
        ;;
esac
