#!/usr/bin/bash
#
# Remove a MySQL/PostgreSQL database for a SmartOS VM.
# Copyright (c) 2016 Joyent Inc., All rights reserved.

set -o errexit
set -o pipefail
#set -o nounset
#set -o xtrace

usage() {
cat << EOF

Usage: $0 [options] TYPE USERNAME

Arguments:
    
    TYPE             Type of database: mysql or postgresql.
    USERNAME         Name of user you want to remove.

Options:
    
    -u               Username to access database.  [use portal credentials]
    -p               Password to access database.  [use portal credentials] 

EOF
exit 2;
}

while getopts "u:p:" OPTION; do
	case $OPTION in
		u)
			DB_USER=$OPTARG;
			;;
		p)
			DB_PASS=$OPTARG;
			;;
		*)
			usage;
			;;
	esac
done

shift $(($OPTIND - 1))
if [[ $# = 2 ]]; then
	DB_TYPE=$1;
	DB_REMOVEUSER=$2;
else
	usage;
fi

export LANG=C
PATH="/opt/local/bin:/opt/local/gnu/bin:/opt/local/sbin:/usr/bin:/usr/sbin";

remove_mysqldbuser() {
        hash mysql 2>/dev/null || { echo "* ERROR - mysql was not found in your PATH." && exit 2; }

        [[ ! `pgrep mysqld` ]] && echo "* ERROR - mysql must be running to remove a user." && exit 2;

        mysql -u${DB_USER} -p${DB_PASS} -e "select version();" > /dev/null 2>&1 || \
                { echo "* ERROR - Can't connect with username password specified." && exit 2; }

	mysql -u${DB_USER} -p${DB_PASS} -e "delete from mysql.user where User='${DB_REMOVEUSER}';" > /dev/null 2>&1 || \
		{ echo "* ERROR - There was an error removing the user." && exit 2; }

	echo "* Removed MySQL user ${DB_REMOVEUSER}.";
}
remove_postgresdbuser() {
        hash psql 2>/dev/null || { echo "* ERROR - psql was not found in your PATH." && exit 2; }

        export PGPASSWORD=${DB_PASS};

        [[ ! `pgrep postgres` ]] && echo "* ERROR - postgresql must be running to remove a user." && exit 2;

        psql -U ${DB_USER} -c "select datname from pg_database;" > /dev/null 2>&1 || \
                { echo "* ERROR - Can't connect with username password specified." && exit 2; }

	[[ ! $(psql -U ${DB_USER} -t -A -c "select usename from pg_user where usename = '${DB_REMOVEUSER}'";) ]] && echo "* ERROR - Username ${DB_REMOVEUSER} doesn't exist." && exit 2;

	DB_POSTGRES_ID=$(psql -U ${DB_USER} -t -A -c "select usesysid from pg_shadow where usename='postgres'";);
	DB_REMOVEUSER_ID=$(psql -U ${DB_USER} -t -A -c "select usesysid from pg_shadow where usename='${DB_REMOVEUSER}'";);

	psql -U ${DB_USER} -c "update pg_database set datdba='${DB_POSTGRES_ID}' where datdba='${DB_REMOVEUSER_ID}';" > /dev/null 2>&1 || \
		{ echo "* ERROR - There was an error removing the user." && exit 2; }
	psql -U ${DB_USER} -c "drop user ${DB_REMOVEUSER};"

#	psql -U ${DB_USER} -c "revoke all on database dbname from username; drop user ${DB_REMOVEUSER};" > /dev/null 2>&1
#	[[ $? > 0 ]] && echo "* ERROR - There was an error removing the user." && exit 2;

	echo "* Removed PostgreSQL user ${DB_REMOVEUSER}.";
}

case $DB_TYPE in
	mysql)
		DB_USER=${DB_USER:-root};
		DB_PASS=${DB_PASS:-$(mdata-get mysql_pw 2> /dev/null)} || DB_PASS="null";
		remove_mysqldbuser;
		;;
	postgresql)
		DB_USER=${DB_USER:-postgres};
		DB_PASS=${DB_PASS:-$(mdata-get pgsql_pw 2> /dev/null)} || DB_PASS="null";
		remove_postgresdbuser;
		;;
	*)
		usage;
		;;
esac
