#!/usr/bin/bash
#
# Shuts down a VM.
# Copyright (c) 2013 Joyent Inc., All rights reserved.

export LANG=C
PATH="@PREFIX@/bin:@PREFIX@/gnu/bin:@PREFIX@/sbin:/usr/bin:/usr/sbin";

# Un-mount NFS filesystems first.
for i in $(df -F nfs 2>/dev/null | egrep -v "^Filesystem" | awk '{ print $1 }'); do 
        umount $i;
done

# Shut down.
shutdown -y -i5 -g0
