#!/usr/bin/bash
#
# Set the hostname of a SmartMachine.
# Joyent 2012.

usage() {
cat << EOF

Usage: $0 HOSTNAME

EOF
exit 2;
}

[[ ! $1 ]] && usage;

PATH="/opt/local/bin:/opt/local/gnu/bin:/opt/local/sbin:/usr/bin:/usr/sbin";
HOSTNAME=$1
ZONENAME=$(zonename);
IP_EXTERNAL=$(ifconfig -a | grep -A 1 net0 | awk '/inet/ { print $2 }');
IP_INTERNAL=$(ifconfig -a | grep -A 1 net1 | awk '/inet/ { print $2 }');

echo "* Setting hostname for ${ZONENAME}..";

cat > /etc/inet/hosts << EOF
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# Internet host table
#
::1		localhost
127.0.0.1	localhost loghost
${IP_EXTERNAL}	${HOSTNAME}
${IP_INTERNAL}	${ZONENAME}	loghost
EOF

echo "${HOSTNAME}" > /etc/nodename

hostname ${HOSTNAME}

echo "* Changed hostname to ${HOSTNAME}.  You will need to reboot.";
