#!/usr/bin/bash
#
# Set the hostname of a VM.
# Copyright (c) 2013 Joyent Inc., All rights reserved.

usage() {
cat << EOF >&2

Usage: $0 HOSTNAME

EOF
exit 2;
}

[[ ! $1 ]] && usage;

export LANG=C
PATH="@PREFIX@/bin:@PREFIX@/gnu/bin:@PREFIX@/sbin:/usr/bin:/usr/sbin";
vm_host="$1";
vm_uuid=$(zonename);
ip_external=$(ifconfig -a | grep -A 1 net0 | awk '/inet/ { print $2 }');
ip_internal=$(ifconfig -a | grep -A 1 net1 | awk '/inet/ { print $2 }');

echo "* Setting hostname for ${vm_uuid}..";

cat > /etc/inet/hosts << EOF
::1		localhost
127.0.0.1	localhost loghost
${ip_external}	${vm_host}
${ip_internal}	${vm_uuid}	loghost
EOF

echo "${vm_host}" > /etc/nodename

hostname ${vm_host}

echo "* Changed hostname to ${vm_host}.  You will need to reboot.";
